name: Publish

on:
  release:
    types: [published]

jobs:
  run-tests:
    name: Run tests
    permissions:
      contents: write
    uses: ./.github/workflows/test.yml

  publish:
    needs: run-tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
